#-------------------------------
# General Site Settings
title: Melanye

#-------------------------------
# Author Settings
author:
  name: Melanye Lainez
  image: 01.jpg
  say-hello: Hola, soy <strong>Melanye Lainez</strong>
  bio: Tengo 19 años, nací el 23 de febrero del 2001, soy ecuatoriana.
       Los instrumentos musicales me gustan mucho, sé tocar guitarra y bajo. Me encantaría aprender a tocar piano. 
       Me gusta mucho todo lo que tienen que ver con computadoras, aparatos electrónicos y programas. Aparte de ello, me gustan los idiomas por ahora solo he estudiado el inglés, pero me gustaría aprender francés.


#-------------------------------
# Contact links
facebook: https://facebook.com/ # Add your Facebook handle
instagram: https://instagram.com/ # Add your Instagram handle


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: melanye_26 # Add instagram username
